services:
  postgres:
    container_name: decrypt-db
    image: postgres
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
