import type { Metadata } from 'next'

import AuthSessionWrapper from '@/components/shared/AuthSessionProvider'
import SmoothScrollProvider from '@/components/shared/CustomSmoothScrollProvider'
import { ThemeProvider } from '@/components/themes/theme-provider'
import { codeFont } from '@/lib/fonts'
import Navbar from '@/components/shared/Navbar'
import { TLayoutProps } from '@/types'
import '../styles/globals.css'


export const metadata: Metadata = {
  title: 'DeCrypt',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }: TLayoutProps) {
  return (
    <html lang="en">
      <body className={codeFont.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <AuthSessionWrapper>
            <SmoothScrollProvider>
              <Navbar />
              <main>{children}</main>
            </SmoothScrollProvider>
          </AuthSessionWrapper>
        </ThemeProvider>
      </body>
    </html>
  )
}
